# Generated by Django 4.1.4 on 2024-01-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
    ]
