# Generated by Django 5.0.1 on 2024-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0003_salesmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='item_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
