# Generated by Django 5.0.1 on 2024-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0005_salesmaster_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
