# Generated by Django 5.0.1 on 2024-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0007_itemsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmaster',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('CANCLED', 'CANCLED')], max_length=100, null=True),
        ),
    ]
