# Generated by Django 5.0.1 on 2024-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0008_salesmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('CANCLED', 'CANCLED')], default='PENDING', max_length=100, null=True),
        ),
    ]
